# Generated by Django 4.1.1 on 2022-09-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='name',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
